/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alivia08052025;

/**
 *
 * @author LABP1KOMP
 */
public class FormStudent extends javax.swing.JFrame {

    /**
     * Creates new form FormStudent
     */
    public FormStudent() {
        initComponents();
        this.bersihLayar();
            
    }
    public void bersihLayar() {
        txtNama.setText("");
        txtAlamat.setText("");
        txtUmur.setText("");
        txtMatematika.setText("");
        txtBhsInggris.setText("");
        txtIlmuPengetahuan.setText("");
        txtRatarata.setText("");
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUmur = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMatematika = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBhsInggris = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIlmuPengetahuan = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtRatarata = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nama");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 60, 20);

        txtNama.setText("jTextField1");
        getContentPane().add(txtNama);
        txtNama.setBounds(160, 30, 250, 20);

        jLabel2.setText("Alamat");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 33, 20);

        txtAlamat.setText("jTextField2");
        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });
        getContentPane().add(txtAlamat);
        txtAlamat.setBounds(160, 60, 250, 20);

        jLabel3.setText("Umur");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 90, 40, 14);

        txtUmur.setText("jTextField3");
        txtUmur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUmurActionPerformed(evt);
            }
        });
        getContentPane().add(txtUmur);
        txtUmur.setBounds(160, 90, 250, 20);

        jLabel4.setText("Matematika");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 120, 55, 10);

        txtMatematika.setText("jTextField4");
        txtMatematika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatematikaActionPerformed(evt);
            }
        });
        getContentPane().add(txtMatematika);
        txtMatematika.setBounds(160, 120, 250, 20);

        jLabel5.setText("Bhs.Inggris");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 150, 70, 14);

        txtBhsInggris.setText("jTextField5");
        txtBhsInggris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBhsInggrisActionPerformed(evt);
            }
        });
        getContentPane().add(txtBhsInggris);
        txtBhsInggris.setBounds(160, 150, 250, 20);

        jLabel6.setText("Ilmu Pengetahuan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 180, 100, 14);

        txtIlmuPengetahuan.setText("jTextField6");
        getContentPane().add(txtIlmuPengetahuan);
        txtIlmuPengetahuan.setBounds(160, 180, 250, 20);

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        getContentPane().add(btnProses);
        btnProses.setBounds(10, 210, 410, 23);

        jLabel7.setText("Rata-rata");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 240, 70, 14);

        txtRatarata.setText("jTextField1");
        getContentPane().add(txtRatarata);
        txtRatarata.setBounds(160, 240, 250, 20);

        setSize(new java.awt.Dimension(449, 341));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatematikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatematikaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatematikaActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        StudentRecord student = new StudentRecord();
        student.setName(txtNama.getText());
        student.setAddress(txtAlamat.getText());
        student.setAge(Integer.parseInt(txtUmur.getText()));
        student.setMathGrade(Double.parseDouble(txtMatematika.getText()));
        student.setEnglishGrade(Double.parseDouble(txtBhsInggris.getText()));
        student.setScienceGrade(Double.parseDouble(txtIlmuPengetahuan.getText()));
        txtRatarata.setText(String.valueOf(student.getAverage()));
    }//GEN-LAST:event_btnProsesActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void txtBhsInggrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBhsInggrisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBhsInggrisActionPerformed

    private void txtUmurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUmurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUmurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtBhsInggris;
    private javax.swing.JTextField txtIlmuPengetahuan;
    private javax.swing.JTextField txtMatematika;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtRatarata;
    private javax.swing.JTextField txtUmur;
    // End of variables declaration//GEN-END:variables
}
